### ISSUE TITLE
Dropbox not syncing and support wanting us to upgrade.

### ISSUE THREAD

**Issue by terjekv** [flathub/com.dropbox.Client#300]
We're having an issue where Dropbox refuses to sync, it is giving us `HTTPPost unexpected error: NS_ERROR_STORAGE_BUSY:` and Dropbox support wants us to upgrade. Is there an ETA on #299 to make support happy? :)

**Comment by wjt** [comment]
I merged it without testing, let me know if it doesn't work!

**Comment by terjekv** [comment]
Great, thanks! Let's see how long it takes before the repo sees it. :)

**Comment by terjekv** [comment]
Apologies for the late reply. The update went in but out issues remain. We are talking to Dropbox support now that they at least can't blame the version. Thank you for you help!
